force-app/main/default/objects/Lease__c/Lease__c.object-meta.xml
<CustomObject>
    <label>Lease</label>
    <nameField>
        <label>Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Leases</relationshipLabel>
    <relationshipName>Leases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectChildControl.cls
public class ProjectChildControl {
    
    public static void controlParent(list<Lease__c> newlist){
        set<id> oldid= new set<id>();
        for(Lease__c ch: newlist){
            oldid.add(ch.Property__c);
        }
        list<AggregateResult> agriResult=[Select Property__c,Count(id)counting from Lease__c where Property__c in: oldid
                                          Group by Property__c];
        map<id,integer> result= new map<id,integer>();
        for(AggregateResult ar:agriResult){
            result.put((id)ar.get('Property__c'),(integer)ar.get('counting'));
        }
        for(Lease__c  ch :newlist){
            integer count= result.get(ch.Property__c);
            if(count==null){
                count=0;
            }
            if(count>=3){
                ch.addError('not morethan 3 childs');
                }
            
        }
      }
}