force-app/main/default/objects/Lease__c/Lease__c.object-meta.xml
<CustomObject>
    <label>Lease</label>
    <nameField>
        <label>Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Tenant__c</referenceTo>
    <relationshipLabel>Leases</relationshipLabel>
    <relationshipName>Leases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tenant__c/Tenant__c.object-meta.xml
<CustomObject>
    <label>Tenant</label>
    <nameField>
        <label>Tenant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tenant__c/fields/total__c.field-meta.xml
<CustomField>
    <fullName>total__c</fullName>
    <label>total rent amout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tenant__c/fields/Total_Leases__c.field-meta.xml
<CustomField>
    <fullName>Total_Leases__c</fullName>
    <label>Total Leases</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RollupTenent1.cls
public class RollupTenent1 {
    public static void rollUpSumCount1(List<Lease__c> newlist, Map<Id, Lease__c> oldmap) {
        Set<Id> TenantIds = new Set<Id>();

        
        if (newlist != null && oldmap == null) {
            for (Lease__c l : newlist) {
                if (l.Tenant__c != null) {
                    TenantIds.add(l.Tenant__c);
                }
            }
        }

        
        if (newlist != null && oldmap != null) {
            for (Lease__c l : newlist) {
                if (l.Tenant__c != null) {
                    Lease__c oldLease = oldmap.get(l.Id);
                    if (l.Rent_Amount__c != oldLease.Rent_Amount__c || l.Tenant__c != oldLease.Tenant__c) {
                        TenantIds.add(l.Tenant__c);
                        TenantIds.add(oldLease.Tenant__c);
                    }
                }
            }
        }

        // Check if only oldmap is provided
        if (newlist == null && oldmap != null) {
            for (Lease__c l : oldmap.values()) {
                if (l.Tenant__c != null) {
                    TenantIds.add(l.Tenant__c);
                }
            }

        }

        if (!TenantIds.isEmpty()) {
            List<AggregateResult> arr = [
                SELECT Tenant__c,
                       SUM(Rent_Amount__c) totalAmount,
                       COUNT(Id) childcount
                FROM Lease__c
                WHERE Tenant__c IN :TenantIds
                GROUP BY Tenant__c
            ];

            List<Tenant__c> tenantList = new List<Tenant__c>();

            for (AggregateResult arrEach : arr) {
                Tenant__c tenant = new Tenant__c();
                tenant.Id = (Id) arrEach.get('Tenant__c');
                tenant.Total_Leases__c = (Integer) arrEach.get('childcount');
                tenant.total__c = (Decimal) arrEach.get('totalAmount');
                tenantList.add(tenant);
            }

            if (!tenantList.isEmpty()) {
                upsert tenantList;
            }
        }
    }
}