force-app/main/default/objects/Clients__c/Clients__c.object-meta.xml
<CustomObject>
    <label>Clients</label>
    <nameField>
        <label>Clients Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clients__c/fields/Active_status__c.field-meta.xml
<CustomField>
    <fullName>Active_status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Clients__c/fields/Name_of_the_client__c.field-meta.xml
<CustomField>
    <fullName>Name_of_the_client__c</fullName>
    <label>Name of the client</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Clients__c/fields/phone__c.field-meta.xml
<CustomField>
    <fullName>phone__c</fullName>
    <description>mobile no</description>
    <label>phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/CreateNewRecordClientHandler.cls
public class CreateNewRecordClientHandler {
   /* public static void newRecord(){
        Clients__c cl = new Clients__c();
            cl.Name='record11';
            cl.Name_of_the_client__c = 'record11';
            cl.Active_status__c =true;
        insert cl;
    }*/
    public Static void RecordUdatewinserted(list<Clients__c> newlist){
        
        for(Clients__c acc : newlist){
            acc.phone__c = '8713893478';
            
        }
        
        
    }
}