force-app/main/default/objects/demo1__c/demo1__c.object-meta.xml
<CustomObject>
    <label>demo1</label>
    <nameField>
        <label>demo1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>demos1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/demo2__c/demo2__c.object-meta.xml
<CustomObject>
    <label>demo2</label>
    <nameField>
        <label>demo2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>demos2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/demo2__c/fields/demo1__c.field-meta.xml
<CustomField>
    <fullName>demo1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>demo1</label>
    <referenceTo>demo1__c</referenceTo>
    <relationshipLabel>demos2</relationshipLabel>
    <relationshipName>demos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Demo2Create.cls
public class Demo2Create {
    
    public static void method1(list<demo1__c> demo1List){
        list<demo2__c> demo2List = new list<demo2__c>();
        for(demo1__c demo1:demo1List){
           demo2__c demo2 = new demo2__c();
           demo2.Name = 'Test4';
           
           demo2List.add(demo2);
           system.debug(demo2); 
          
           
            
        
        
        }
        
        if(!demo2List.isempty())
            insert demo2List;
        
        
    }

}