force-app/main/default/objects/Child1__c/Child1__c.object-meta.xml
<CustomObject>
    <label>Child1</label>
    <nameField>
        <label>Child1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Childs1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Child1__c/fields/Amount1__c.field-meta.xml
<CustomField>
    <fullName>Amount1__c</fullName>
    <label>Amount1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Child1__c/fields/Choose_Parent1__c.field-meta.xml
<CustomField>
    <fullName>Choose_Parent1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Choose_Parent1</label>
    <referenceTo>Parent1__c</referenceTo>
    <relationshipLabel>Childs1</relationshipLabel>
    <relationshipName>Childs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parent1__c/Parent1__c.object-meta.xml
<CustomObject>
    <label>Parent1</label>
    <nameField>
        <label>Parent1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>parents1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parent1__c/fields/Above_1000__c.field-meta.xml
<CustomField>
    <fullName>Above_1000__c</fullName>
    <label>Above_1000</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parent1__c/fields/Below_1000__c.field-meta.xml
<CustomField>
    <fullName>Below_1000__c</fullName>
    <label>Below_1000</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Child1Handler.cls
public class Child1Handler{
    public static void method1(list<Child1__c> newlist,map<id,Child1__c> oldlist){
        list<Parent1__c> parentIds = new list<Parent1__c>();
        
        if(newlist != null){
            for(Child1__c c:newlist){
                if(c.Amount1__c != null && c.Choose_Parent1__c != null){
                     if(c.Amount1__c > 1000){
                          Parent1__c ch = [select id,Above_1000__c from Parent1__c where id = :c.Choose_Parent1__c limit 1];
                          if(ch.Above_1000__c == null)
                               ch.Above_1000__c = 0;
                          ch.Above_1000__c = ch.Above_1000__c + 1  ;
                          parentIds.add(ch);
                      if(oldlist != null)  { 
                         if(oldlist.get(c.Id).Choose_Parent1__c != null){
                               Parent1__c cc = [select id,Above_1000__c from Parent1__c where id = :oldlist.get(c.Id).Choose_Parent1__c limit 1];
                               cc.Above_1000__c = cc.Above_1000__c - 1;
                               parentIds.add(cc);
                          }
                      }
                    }
                    if(c.Amount1__c <= 1000){
                         Parent1__c ch = [select id,Below_1000__c from Parent1__c where id = :c.Choose_Parent1__c limit 1];
                         if(ch.Below_1000__c == null)
                              ch.Below_1000__c = 0;
                      
                         ch.Below_1000__c = ch.Below_1000__c + 1  ;
                         parentIds.add(ch);
                    if(oldlist != null)  { 
                         if(oldlist.get(c.Id).Choose_Parent1__c != null){
                               Parent1__c cc = [select id,Below_1000__c from Parent1__c where id = :oldlist.get(c.Id).Choose_Parent1__c limit 1];
                               cc.Below_1000__c = cc.Below_1000__c - 1;
                               parentIds.add(cc);
                          }
                      }
                                               
                    }
                        
                 }
                    
              }
          }
        if(newlist==null && oldlist !=null){
           system.debug(oldlist);
          
        }
            
          if(!parentIds.isempty())
              update parentIds;
      }
 }